### ISSUE TITLE
is it possible to make a amd version using HSA COMPUTE with OpenCL or a directx12 version of this 

### ISSUE THREAD

**Issue by Pickymarker** [34j/so-vits-svc-fork#101]
is it possible to make a amd version using HSA COMPUTE with OpenCL or a directx12 version of this

**Comment by GarrettConway** [comment]
Are you not able to use CPU inference?

**Comment by Pickymarker** [comment]
no want the speed of gpu not cpu

**Comment by Pickymarker** [comment]
and if it had HSA COMPUTE with OpenCL it would run good on amd and if that's not doable then at least a directx12 version.

**Comment by GarrettConway** [comment]
You are welcome to attempt to use the PyTorch ROCm build (it may be as simple as just installing this as your torch, but I have no experience with ROCm build), however it only runs on Linux. Unless another contributor comes in to do this though, I seriously doubt any existing contributor will attempt to explicitly add support as I believe we likely do not have AMD equipment to test this and are focusing on other areas.

**Comment by GarrettConway** [comment]
Pytorch ROCm install can be found here: https://pytorch.org/get-started/locally/
You can try just forcing that as your torch version.

**Comment by Pickymarker** [comment]
what about this https://github.com/microsoft/antares

**Comment by 34j** [comment]
Migrate to #120
