### ISSUE TITLE
LOG.info not printing at all? (v1.3.2)

### ISSUE THREAD

**Issue by Lordmau5** [34j/so-vits-svc-fork#104]
**Describe the bug**
LOG.info calls aren't printing anything to the console
Example `LOG.info(f"====> Epoch: {epoch}, cost {durtaion} s")`

**To Reproduce**
Running `svc train` with the specific model path should do the trick

**Additional context**
I can see LOG.warning calls, especially since I've added those as well, and I couldn't spot anything in regards to the log level being set to only warnings instead of info. I remember seeing info logs in the Google colab I've used though (Might've been with the code from the main repository though)

**Comment by 34j** [comment]
Warning is the (Python) default level.

**Comment by Lordmau5** [comment]
According to this line it should be set to INFO though, right?
https://github.com/34j/so-vits-svc-fork/blob/main/src/so_vits_svc_fork/__main__.py#L35

**Comment by BlueAmulet** [comment]
Various parts of the code spawn their own process, these new processes have default logger and level and nothing will end up calling init_logger in them.

Ideally init_logger should be moved to it's on file, and everything that currently does `from logging import getLogger` would be changed to get a logger from the new file, so that it'll always initialize the logger with Rich printing and INFO level. Made that change locally, but

Issues:
init_logger currently also sets up a log file, but multiple processes trying to access the same log file or make multiple isn't ideal.
rich printing and tqdm minorly conflict, in that when logging occurs it'll write it's output to the end of the progress bar on screen rather than to a new line, rich has it's own progress bar but it's kind of small and missing a lot of information?

**Comment by BlueAmulet** [comment]
Just learned that tqdm has `tqdm.rich.tqdm` which makes a tqdm style progress bar, but using rich and the bar doesn't mangle when logging. could just do `from tqdm.rich import tqdm as pbar`

For the IS_COLAB part, there is logging_redirect_tqdm in tqdm.contrib.logging which fixes the progress bar duplication, this seems to work okay:
```
from tqdm import tqdm

def pbar(*args, **kwargs):
    with logging_redirect_tqdm():
        for val in tqdm(*args, **kwargs):
            yield val
```

The idea is that anything currently using tqdm would be changed to use `.pbar(thing)` from this new logging module.

**Comment by BlueAmulet** [comment]
It wouldn't be? It's taking advantage of the import once design of python modules to initialize rich logging and info level as well as making the code needed to get that smaller. Otherwise init_logger also has to pointlessly check if it's already done it's work and avoid doing it again.

```
from .__main__ import init_logger
from logging import getLogger
init_logger()
LOG = getLogger(__name__)
```

to just

```
from logger import getLogger
LOG = getLogger(__name__)
```

Where it's currently already just two lines in most files to handle logging.

**Comment by 34j** [comment]
I cannot reproduce this issue. Can you please explain more about this?

The getLogger change is not necessary and I am sorry but I don't understand what you are talking about.

**Comment by Lordmau5** [comment]
Example log file of running with the up-to-date code on your repository:
[so_vits_svc_fork.log](https://github.com/34j/so-vits-svc-fork/files/11068415/so_vits_svc_fork.log)

Since it didn't log anything besides the version, here's a screenshot of what the terminal showed:
![image](https://user-images.githubusercontent.com/1345036/227707115-ad240878-06e7-47d2-a835-3153e691bb87.png)

___

Example log file with the changes I made:
[so_vits_svc_fork.log](https://github.com/34j/so-vits-svc-fork/files/11068418/so_vits_svc_fork.log)

Additionally, a screenshot, too:
![image](https://user-images.githubusercontent.com/1345036/227707169-4ae54d2a-11a3-4c87-a284-897c8e95deba.png)

**Comment by 34j** [comment]
I was able to reproduce it in the new environment. Okay, if you are so motivated, make a flag in __init__.py to indicate if the entry point is from __main__.py and call init_logger() only in that case. Your ideas are unacceptable.

**Comment by 34j** [comment]
There must be some other solution, though I can't think of any right now...

**Comment by Lordmau5** [comment]
> There must be some other solution, though I can't think of any right now...

What do you mean "other solution"? The solution that I provided in the pull request works.
I didn't modify any internal logging modules or their methods, such as `getLogger` like you said.
All I did was do a wrapper class that is properly instanciated when it's being used in files.

The current code you have is only getting a standard logger without any configuration, which means it had it's defaults.

However, that means that it also doesn't have proper formatting (or even the RichHandler) besides in the main file.

This addresses that problem.

Additionally, I feel adding a launch argument to set the actual log level might be good to have, too
Such as `--log=INFO` or similar

**Comment by 34j** [comment]
```shell
python -c "import so_vits_svc_fork.train"
python -c "import so_vits_svc_fork.__main__"
```
```shell
> python -c "import so_vits_svc_fork.train"
> python -c "import so_vits_svc_fork.__main__"
[20:17:49] INFO     [20:17:49] Version: 1.3.4           
```
I do not want to or will not merge code that does not meet these two requirements.

**Comment by 34j** [comment]
Does your code meet these?

**Comment by Lordmau5** [comment]
Yep, just ran these
![image](https://user-images.githubusercontent.com/1345036/227714539-e138ecbe-25ca-4201-9f26-87eb3ad13387.png)

I fully understand that you don't want to merge code that doesn't meet specific requirements.
If there's anything else you want me to test, I'd be more than happy to 😁

I should mention I'm not able to edit anything until tomorrow because I'll be gone for today

**Comment by 34j** [comment]
Sorry, I meant this.
```
python -c "import so_vits_svc_fork.__main__;from logging import getLogger;getLogger().info('hello')"
python -c "import so_vits_svc_fork.train;from logging import getLogger;getLogger().info('hello')"
```
Only the first code should produce output. In other words, it is not a good idea to change the Handler etc when using it as a module.
Though I can certainly understand the opinion that no one may use this package as a module...

**Comment by 34j** [comment]
It is enough to start up tensorboard for me and I don't want to touch this horrible problem for a while.

**Comment by Lordmau5** [comment]
Yeah I personally don't use Tensorboard but I'd like some extra information in the console window haha

![image](https://user-images.githubusercontent.com/1345036/227715051-7debc032-526f-4fee-9f81-4f9917584b7f.png)
Those do produce the wrong results as you mentioned.

Would it in that case be better to instead have a launch parameter as I proposed, such as `--log=LOG_LEVEL`, which then allows finer control?

`__main__` would still use the default that we have, but we could supply the log level additionally through this for the other places where it uses the logger

**Comment by 34j** [comment]
```
from .__main__ import init_logger
init_logger()
```
Actually, the behavior you are describing can be easily implemented by simply adding these two lines to __init__.py in the first place.
Why BlueAmulet gives me a low rating mark is a mystery to me.

**Comment by Lordmau5** [comment]
Oh wait, there's an init.py file? I didn't even notice that haha

Additionally though, the `LOG.info(f"Version: {__version__}")` and `LOG.debug("Test mode is on.")` need to be moved out of the `initLogger` method

Otherwise we get this every single time something happenscreated.
![image](https://user-images.githubusercontent.com/1345036/227715759-19d9502c-96d6-4026-a998-0b25f936d414.png)

**Comment by 34j** [comment]
It is a multi-processing problem that requires some refactoring to solve, but there is absolutely no need to make the major changes that BlueAmlet mentions.

**Comment by Lordmau5** [comment]
> It is a multi-processing problem that requires some refactoring to solve, but there is absolutely no need to make the major changes that BlueAmlet mentions.

Understood, in that case please keep the pull request closed and I can look into making a new one that would fix those issues in another one soon

I guess for now I'll just keep `init_logger()` inside the `__init__.py` file and comment out the 2 `LOG.` calls inside `__main__.py` :D

**Comment by 34j** [comment]
Glad to finally get the word out. Now I can sleep peacefully.

**Comment by BlueAmulet** [comment]
> Why BlueAmulet gives me a low rating mark is a mystery to me. I rather like to give it to him.
I gave you a Confused Face emoji, because I was confused about what you said before.

Yes you are correct, there was no need to make the major changes that I proposed, simply calling init_logger from \_\_init\_\_.py would have been enough to get the behavior that Lordmau5 and I desired.

**Comment by 34j** [comment]
I see, I misunderstood. I am very sorry. I withdraw my statement.

The repository had grown too large and I had lost my mental capacity (excuse).

**Comment by Lordmau5** [comment]
@BlueAmulet Could you test with the latest code as well and see if it's a similar result to what you expected, too?

**Comment by Lordmau5** [comment]
Gonna assume this is working properly for others, too - I've not noticed any more issues myself
