### ISSUE TITLE
Failed install

### ISSUE THREAD

**Issue by xdanielc** [34j/so-vits-svc-fork#108]
**Describe the bug**
Building wheels for collected packages: fairseq
  Building wheel for fairseq (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for fairseq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [1423 lines of output]
  
  
**To Reproduce**
Python version 3.10.6
Windows 10, running cmd as administrator

**Comment by 34j** [comment]
This is a common problem. Look at the top of the error message.

**Comment by barryanders** [comment]
I had the same problem. This helped me:

```bash
git clone https://github.com/pytorch/fairseq
cd fairseq
pip install --editable .
```

I was able to succeed with `pip install -U so-vits-svc-fork` after that.
