### ISSUE TITLE
svcg is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by kotaxyz** [34j/so-vits-svc-fork#111]
**Describe the bug**

i get this error when pip install -U so-vits-svc-fork
also svcg dosnt work

 C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

(so-vits-fork-new) C:\Users\Genesis>svcg
'svcg' is not recognized as an internal or external command,
operable program or batch file.

(so-vits-fork-new) C:\Users\Genesis>

**To Reproduce**
conda activate so-vits-fork
pip install -U so-vits-svc-fork
svcg

**Additional context**

**Comment by 34j** [comment]
This will help:
https://stackoverflow.com/questions/12685202/how-do-i-get-crtdbg-h-file

**Comment by kotaxyz** [comment]
thanks for your reply i was trying to install visual studio c++ dependinces on my own it didnt work with windows 10 sdk and old microsoft visual c++ i fixed it by deleting those and installing windows 11 sdk and microsoft visual c++ 2022
