### ISSUE TITLE
Meaningless warning occurs if file name contains hyphen in `pre-flist_config`.

### ISSUE THREAD

**Issue by 34j** [34j/so-vits-svc-fork#121]
**Describe the bug**

**To Reproduce**

**Additional context**

**Comment by Lordmau5** [comment]
Would be around here - https://github.com/34j/so-vits-svc-fork/blob/main/src/so_vits_svc_fork/preprocess_flist_config.py#L38

Additionally, I notice it also has a pattern match for `.wav` in there instead of any audio file

**Comment by 34j** [comment]
Pattern matching is not a problem.

**Comment by Lordmau5** [comment]
Ah okay, just noticed it and thought I'd mention it because you updated the README to allow any format as the file ending :D
