### ISSUE TITLE
svcg infer only uses dio f0 prediction method 

### ISSUE THREAD

**Issue by Satisfy256** [34j/so-vits-svc-fork#125]
When using svcg to infer to an audio file, it seems to be only using dio and changing the f0 prediction method makes no difference. 
I changed it to crepe by manually changing lines in .py scrips with f0_method: Literal["crepe", "crepe-tiny", "parselmouth", "dio", "harvest"] = "dio" to "crepe".
Also I think it would be better if pitch was set at 0 and not 12 when you start svcg.

**Comment by 34j** [comment]
I believe this was fixed in 1.4.1 about 20 minutes ago, have you tried it?

**Comment by Satisfy256** [comment]
> I believe this was fixed in 1.4.1 about 20 minutes ago, have you tried it?

Yes I updated to 1.4.1 and it's fixed. Thanks a lot! I only downloaded an hour ago and the version was 1.3.6.
