### ISSUE TITLE
svc pre-resample resamples to 22 kHz and then to 44 kHz

### ISSUE THREAD

**Issue by Satisfy256** [34j/so-vits-svc-fork#127]
I have wav files in the dataset_raw in mono 44.1 kHz sample rate. When I run svc pre-resample, the files are saved in dataset folder and when I played them I noticed that they sound lower quality.
When I checked with a spectrogram, I noticed that the samples were half quality.
![image](https://user-images.githubusercontent.com/101394399/227764670-ca16c8d5-489f-49a9-b563-ff22fd356cbf.png)

Workaround: copy the wavs from dataset_raw to dataset folder.

**Comment by 34j** [comment]
This worst ever bug has made it necessary to retrain all my models......

**Comment by Satisfy256** [comment]
> This worst ever bug has made it necessary to retrain all my models......

RIP. I always check all audio files with spectograms.
Also the Auto Play in svcg also plays at 22 kHz.

**Comment by 34j** [comment]
@allcontiributors add Satisfy256 bug
