### ISSUE TITLE
Failed to build fairseq

### ISSUE THREAD

**Issue by dhstsw** [34j/so-vits-svc-fork#142]
**Describe the bug**
When processing:
venv\Scripts\pip.exe install so-vits-svc-fork
Installer exits, first with 2 warnings and then with a file not found error:

"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IJ:\SoftVC VITS\venv\include" -IC:\Users\dhs\AppData\Local\Programs\Python\Python310\include -IC:\Users\dhs\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /EHsc /Tpfairseq/clib/libbleu/libbleu.cpp /Fobuild\temp.win-amd64-cpython-310\Release\fairseq/clib/libbleu/libbleu.obj -std=c++11 -O3
      cl : warning della riga di comando D9002 : l'opzione sconosciuta '-std=c++11' verr… ignorata
      cl : warning della riga di comando D9002 : l'opzione sconosciuta '-O3' verr… ignorata
      libbleu.cpp
      C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: Non Š possibile aprire il file inclusione: 'crtdbg.h': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

![image](https://user-images.githubusercontent.com/59790194/227802364-46f3e62b-00db-4120-84c5-04d48e7b5009.png)      
**To Reproduce**
run install.bat

**Additional context**
-Fresh Python 3.10.10 install
-Fresh Visual Studio Install
-Contents of "cudnn-windows-x86_64-8.8.1.3_cuda11-archive.zip" copied inside C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\

Same result with anaconda (skipping the Python check in the bat).
Already tried to unsinstall and reinstall visual studio multiple times.

Spent the whole day trying, no success.
Any hints?

Thanks.

Edit: seems that vs_BuildTools isn't able to install any windows (10 or 11) SDK, no idea why. :(

**Comment by 34j** [comment]
Maybe #111 will help

**Comment by salex97** [comment]
`sudo apt install g++`  solved it for me.

**Comment by 2blackbar** [comment]
taht bat install is a fail, even if it runs once, when you close it, you have no clue how to rerun it again, cmon dev!! i dont want to be spending time on detective work and figure out where exe was gui installed , its not in venv

**Comment by magicianjarden** [comment]
I am also getting the same error, unsolved. Tried to restart and reinstalling the SDK.

**Comment by 34j** [comment]
It seems that using `transformers` eliminates the need to install `fairseq`

**Comment by MaximeHoude** [comment]
> It seems that using `transformers` eliminates the need to install `fairseq` (needs code change)

I'm using the latest repo, manually installing using venv. I do also Failed to build fairseq. How I'm I supposed to be using transformers while `pip install -U so-vits-svc-fork`.
Many thanks!

**Comment by woshitff** [comment]
I also got the same error, and how to replace fairseq with transformers?
