### ISSUE TITLE
Resampling includes the wav files that were said to have been skipped due to being too short, causing errors.

### ISSUE THREAD

**Issue by Desuka-art** [34j/so-vits-svc-fork#145]
Resampling includes the wav files that were said to have been skipped due to being too short, causing errors, the most notable one being 

ValueError: Input signal length=0 is too small to resample from 44100->16000

Getting rid of the ones that are said to be too short fixes the error. Please account for this in the next update.

**Comment by 34j** [comment]
@allcontributors add Desuka-art bug
