### ISSUE TITLE
Illegal combination of I/O devices [PaErrorCode -9993]

### ISSUE THREAD

**Issue by ColdCawfee** [34j/so-vits-svc-fork#146]
**Describe the bug**
Whenever I try the realtime mode, I get this error: "Illegal combination of I/O devices [PaErrorCode -9993]"

**To Reproduce**
1. Press start voice changer button.
2. After a short time, that error appears.

**Comment by 34j** [comment]
@allcontributors add ColdCawfee bug

**Comment by gaotengfei199157** [comment]
windows没问题，Ubuntu有问题，请问解决了吗？
