### ISSUE TITLE
GUI Stuck mac m1

### ISSUE THREAD

**Issue by emmajane1313** [34j/so-vits-svc-fork#187]
After installing in my venv and running svcg the GUI opens but gets stuck / stays on this screen . Have tried uinstalling and reinstalling a few times but keep gettng the same result. I'm using mac m1, does this library only work with windows?

am i missing something?

<img width="1026" alt="Captura de pantalla 2023-03-30 a las 4 26 45 a m" src="https://user-images.githubusercontent.com/72898465/228776857-58bc9a36-fbe1-4dc9-8961-b56346ce35a7.png">

**Comment by xieyumc** [comment]
<img width="1512" alt="Screen Shot 2023-03-30 at 21 15 23" src="https://user-images.githubusercontent.com/47858007/228847818-a14c1a40-b902-47fd-898c-93610380f51d.png">
Mac can run normally

My configuration：MacBook Pro (14-inch, 2021)/Apple M1 Pro/macOS12.6.3

And this is my Conda environments:
[SVC-GUI-backup.yaml.zip](https://github.com/34j/so-vits-svc-fork/files/11111974/SVC-GUI-backup.yaml.zip)

but I think create a new environment and simply run the following code can solve your problem

`conda install pytorch torchvision torchaudio -c pytorch`

`pip install -U so-vits-svc-fork`

**Comment by emmajane1313** [comment]
I just copied ur venv and i could make it to the `svc train -t` step but now get this error 
`[1]    3360 illegal hardware instruction  svc train -t`

i tried downgrading the batch size to around ~3 but error still persists 

I'm on the same machine, MacBook Pro (14-inch, 2021)/Apple M1 Max Pro/macOS13.0.1 (22A400)

**Comment by 34j** [comment]
If it is tensorboard issue, simply remove `-t`

**Comment by xieyumc** [comment]
Oh, sorry, i said "Mac can run normally" mean Mac can run GUI, inference and Realtime voice conversion normally, but training is not allow.Because Mac don't have a GPU that support PyTorch.

Even if the Mac can start training.it will be extremely slow, so I suggest you to use NVIDIA GPU to train.Then you can use Mac to inference and Realtime voice conversion.

**Comment by emmajane1313** [comment]
ah ok , makes sense, thank u

**Comment by hkhking** [comment]
use conda，version of python3 with tk is mismatch in MacOS13
