### ISSUE TITLE
Output files don't have any voice.

### ISSUE THREAD

**Issue by Wolvensdale** [34j/so-vits-svc-fork#202]
Hi, im not sure if this is bug or i have something missing, but my output files don't have any voices at all.

git clone this repo and installing all the requirements just as instructed.
downloading pre-trained model - tubaki (it have three pth files, but i reckon i only need to choose one at a time?)
open GUI using svcg
pointing the model path and config path (tubaki)
recording my voices using audacity ~ 5 seconds just to try
pointing GUI to my voices.wav files
not changing anything, i press "infer"
voices_output.wav are generated but it doesnt have any sound or voices.

this is the log :
[18:47:40] INFO     [18:47:40] Loaded checkpoint                                                           utils.py:426
                    'E:/Sovit/so-vits-svc-fork/logs/44k/tubaki/G_tubaki_200.pth' (iteration 200)
           INFO     [18:47:40] Chunk: Chunk(Speech: False, 262086.0)

Anyone know what the problem is?

**Comment by 34j** [comment]
Perhaps the volume of the input audio is too low.
Are you using the `Default File` preset?
