### ISSUE TITLE
"svc is not a recognized command"

### ISSUE THREAD

**Issue by robbsaber** [34j/so-vits-svc-fork#224]
when I attempt to run 
svc pre-resample
svc pre-config
svc pre-hubert
svc train -t

I get "svc is not a recognized command" etc
what have I done wrong?
Following this video 
https://www.youtube.com/watch?v=tZn0lcGO5OQ&t=124s

**Comment by SatisfiedPeanut** [comment]
use `venv\Scripts\activate` first to create a virtual environment.
when ur powershell has `(venv)` in green, u can run svc successfully

**Comment by robbsaber** [comment]
When I run pip install -U so-vits-svc-fork
I get this error  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]
   note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

I have visual C++ 14.0....

**Comment by BlueAmulet** [comment]
Note that this is not "Microsoft Visual C++ Redistributable" but the "Microsoft C++ Build Tools", I.E a C++ compiler needed to build fairseq. When you install the build tools, make sure to select "Desktop development with C++"
