### ISSUE TITLE
How should I deal with OOM while inferencing

### ISSUE THREAD

**Issue by SatisfiedPeanut** [34j/so-vits-svc-fork#225]
I trained the model and get nice audio while using svc vc to test my voice, but when i use svc infer, I get error like this:
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 294.00 MiB (GPU 0; 4.00 GiB total capacity; 2.61 GiB already allocated; 0 bytes free; 3.42 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I wanna know how to solve it with the batch_size = 1.
Thank you for your work and supporting!

**Comment by sbersier** [comment]
This could happen with long input files. Two solutions:

1) You insist on infering on GPU (cuda): in which case, you should split your input file.

2) You switch to cpu for inference:

`svc infer --help`  will give the available options:

```
Usage: svc infer [OPTIONS] INPUT_PATH

  Inference

Options:
  -o, --output-path PATH          path to output dir
  -s, --speaker TEXT              speaker name
  -m, --model-path PATH           path to model  [default: logs/44k]
  -c, --config-path PATH          path to config  [default: configs/44k/config.json]
  -k, --cluster-model-path PATH   path to cluster model
  -t, --transpose INTEGER         transpose  [default: 0]
  -db, --db-thresh INTEGER        threshold (DB) (RELATIVE)  [default: -20]
  -fm, --f0-method [crepe|crepe-tiny|parselmouth|dio|harvest]
                                  f0 prediction method  [default: dio]
  -a, --auto-predict-f0 / -na, --no-auto-predict-f0
                                  auto predict f0  [default: a]
  -r, --cluster-infer-ratio FLOAT
                                  cluster infer ratio  [default: 0]
  -n, --noise-scale FLOAT         noise scale  [default: 0.4]
  -p, --pad-seconds FLOAT         pad seconds  [default: 0.5]
  -d, --device TEXT               device  [default: cuda]
  -ch, --chunk-seconds FLOAT      chunk seconds  [default: 0.5]
  -ab, --absolute-thresh / -nab, --no-absolute-thresh
                                  absolute thresh  [default: nab]
  -h, --help                      Show this message and exit.
```
As you can see, -d or --device is here to choose between cuda and cpu

So, you can try:

`svc infer --device cpu myfile.wav`

**Comment by SatisfiedPeanut** [comment]
solve it! Thank u
