### ISSUE TITLE
Both svc split and svc  sd can't be used

### ISSUE THREAD

**Issue by 34j** [34j/so-vits-svc-fork#227]
### Discussed in https://github.com/34j/so-vits-svc-fork/discussions/221

<div type='discussions-op-text'>

<sup>Originally posted by **wx40217** April  4, 2023</sup>
Hey I just download the code and try to split my dataset.But when I try this ,it always says "Error: No such command 'split'".However,I can still use the command to train such as "svc pre-resample".Did I miss something?
![image](https://user-images.githubusercontent.com/24869295/229570991-8f5260fa-8686-44b7-8b85-180cb90cd52a.png)
</div>

**Comment by Lordmau5** [comment]
Heads-up that this can be closed since it was answered in the discussion already (`split` instead of `pre-split`)

**Comment by 34j** [comment]
README.md may need fix
