### ISSUE TITLE
'HParams' object has no attribute 'filter_length'

### ISSUE THREAD

**Issue by oliverdjohnston** [34j/so-vits-svc-fork#240]
**Describe the bug**
Whenever I use the infer feature i get this error.
![image](https://user-images.githubusercontent.com/81986077/230240570-9668d33f-bbbe-4b45-8ccd-a01f9a21e9d1.png)
**Additional context**
i've already tried updating and am currently on the latest version

**Comment by TZFC** [comment]
I ran into the same problem. Realized I am using sovits4.0 v2, not sovits4.0. The model config fields are different. 
Feature request: for sovits 4.0 v2 support
