### ISSUE TITLE
ValueError: X has 768 features, but KMeans is expecting 256 features as input.

### ISSUE THREAD

**Issue by Herob527** [34j/so-vits-svc-fork#253]
**Describe the bug**
When I try using inference with cluster in colab, it throws:
`ValueError: X has 768 features, but KMeans is expecting 256 features as input.`

Normal infer works

Command looks like this in colab:
`!svc infer -fm "crepe" -o {NAME}_cluster.out.wav -s "SoW-Celebrimbor" -r 0.1 -m drive/MyDrive/so-vits-svc-fork/logs/44k/ -c drive/MyDrive/so-vits-svc-fork/logs/44k/config.json -k drive/MyDrive/so-vits-svc-fork/logs/44k/kmeans.pt test.wav
`
Where NAME is a string variable
 
**To Reproduce**
On colab train model and use inference with cluster

**Comment by 34j** [comment]
This is caused by a mismatch between the config when the model was created and when the cluster was created; add -t so-vits-svc-4.0v1 after pre-config and retrain the cluster.

**Comment by Herob527** [comment]
Good

Now it works
