### ISSUE TITLE
Newly trained model since Lightning implementation sounds robotic early on

### ISSUE THREAD

**Issue by Lordmau5** [34j/so-vits-svc-fork#270]
**Describe the bug**
Started training a new model in 3.1.4 and noticed it sounded super robotic around 1700 steps in.

(Converted to webm so I could upload them here)
Original:
[original.webm](https://user-images.githubusercontent.com/1345036/230768178-47bb3f5c-bba1-4e3f-9c63-dbe053ed149e.webm)

Generated:
[generated_1700.webm](https://user-images.githubusercontent.com/1345036/230768187-a1cc8142-2f70-42b0-8454-c11693ad79c4.webm)

**To Reproduce**
Start generating a new model with 3.1.4

**Additional context**
The setup (pre-resample, pre-config, pre-hubert) has been done with their default settings.

I saw this commit that fixed the order of the _d optimizer. I've made these changes locally myself and gonna report back on the model once I trained it from scratch again
https://github.com/34j/so-vits-svc-fork/commit/13d63469b0a84ace0dc8848df47dc20538b98770

Additionally, I have no idea if this is intentional and it just needs more iterations.
Does it perhaps not take the legacy checkpoint into account anymore?

**Comment by Lordmau5** [comment]
Even after around 5000 steps it still sounds very robotic. I applied the fix in the commit.

Original:
[original_2.webm](https://user-images.githubusercontent.com/1345036/230769525-46e57712-6d34-41df-90d2-3f029bd6b63b.webm)

Generated:
[generated_5000.webm](https://user-images.githubusercontent.com/1345036/230769534-16c7c764-a593-45ee-b310-5d02d09ddc08.webm)

**Comment by tonyco82** [comment]
same

**Comment by 34j** [comment]
Does the above PR fix this issue?

**Comment by Lordmau5** [comment]
Yup! That indeed helped with 0 steps already (as in, the initial conversion / preparation)
It still seems like there's a bit of metallic shrill, similar to another issue, but I assume that would go away after more training

Original:
[original_3.webm](https://user-images.githubusercontent.com/1345036/230771849-3e6d5d9e-0364-4af1-aa50-903db2a28874.webm)

Generated (0 steps):
[generated_3_0.webm](https://user-images.githubusercontent.com/1345036/230771856-a2bce2e3-a862-4da1-b950-6605dacacaf3.webm)

Generated (~1700 steps):
[generated_3_1700.webm](https://user-images.githubusercontent.com/1345036/230772256-de7d4e9d-e2c6-46f1-b638-af93562dd9e8.webm)

**Comment by ne0escape** [comment]
I left it until 100k steps to see if it would gradually fix up.

Big mistake, still sounds robotic!

**Comment by 34j** [comment]
> Additionally

😇

**Comment by 34j** [comment]
> Yup! That indeed helped with 0 steps already (as in, the initial conversion / preparation)
> It still seems like there's a bit of metallic shrill, similar to another issue, but I assume that would go away after more training
> 
> Original:
> [original_3.webm](https://user-images.githubusercontent.com/1345036/230771849-3e6d5d9e-0364-4af1-aa50-903db2a28874.webm)
> 
> Generated (0 steps):
> [generated_3_0.webm](https://user-images.githubusercontent.com/1345036/230771856-a2bce2e3-a862-4da1-b950-6605dacacaf3.webm)
> 
> Generated (~1700 steps):
> [generated_3_1700.webm](https://user-images.githubusercontent.com/1345036/230772256-de7d4e9d-e2c6-46f1-b638-af93562dd9e8.webm)
> 
> 
> **Additionally**, I stopped the training after that first checkpoint save, and started it again now.
> It said it would start at epoch 79, however, it saved the model and optimizer state **at iteration 0 to logs\44k\G_0** and D_0, instead of 1770 (or whichever one it initially saved it to)
> 
> Letting it run for a bit, it seemed to save at around 891 steps instead of 1770.
> Also, after stopping that, too, and restarting it, it went back to 0

How many gpus are connected to your pc?

**Comment by Lordmau5** [comment]
> How many gpus are connected to your pc?

A single one, 3090. With about 170 audio clips in the dataset I can get around 1.5 iterations per second (which for my use cases is more than enough)

**Comment by 34j** [comment]
In Lightning, global_steps seems to be added every time optimizer.step is called....

**Comment by Lordmau5** [comment]
Could this be helpful in fixing it? https://github.com/Lightning-AI/lightning/issues/17281

**Comment by 34j** [comment]
It is more complicated than I thought, it is also related to tensorboard

**Comment by Lordmau5** [comment]
> It is more complicated than I thought, it is also related to tensorboard

I see, if you have any more things I should test out please tell me! 😁

**Comment by ne0escape** [comment]
Updating everything, but mine sounds like this:

[Original](https://user-images.githubusercontent.com/119090212/230781910-7e92a41a-0e3b-4f2e-b54d-417d60c801e7.webm)
[2200 Steps](https://user-images.githubusercontent.com/119090212/230781899-55503d0f-e5f7-4825-bfb6-6c0986ba5b71.webm)

I'm using pre-resample, pre-config. and svc pre-hubert -fm crepe (I've also tried just svc pre-hubert).

My training set consists of 263 files that range from 1-14 seconds each, adding up to 20 minutes and 36 seconds of data.

I'm hesitant to train it further because I'm afraid that it might result in the same robotic voice I experienced the last time I trained it for 100k steps. It's possible that I'm mistaken, but I'm convinced that everything was working perfectly just a few weeks ago. I even tried a complete reinstall, but unfortunately, it didn't fix the issue.
 
Any idea what I'm doing wrong?

**Comment by 34j** [comment]
> It is more complicated than I thought, it is also related to tensorboard

Might still need additional fix, progress bar displays incomplete

**Comment by 34j** [comment]
> Updating everything, but mine sounds like this:
> 
> [Original](https://user-images.githubusercontent.com/119090212/230781910-7e92a41a-0e3b-4f2e-b54d-417d60c801e7.webm) [2200 Steps](https://user-images.githubusercontent.com/119090212/230781899-55503d0f-e5f7-4825-bfb6-6c0986ba5b71.webm)
> 
> I'm using pre-resample, pre-config. and svc pre-hubert -fm crepe (I've also tried just svc pre-hubert).
> 
> My training set consists of 263 files that range from 1-14 seconds each, adding up to 20 minutes and 36 seconds of data.
> 
> I'm hesitant to train it further because I'm afraid that it might result in the same robotic voice I experienced the last time I trained it for 100k steps. It's possible that I'm mistaken, but I'm convinced that everything was working perfectly just a a week or two ago. I even tried a complete reinstall, but unfortunately, it didn't fix the issue.
> 
> Any idea what I'm doing wrong?

As you see, I just fixed this issue right now

**Comment by ne0escape** [comment]
Just updated to 3.1.6, but getting this error:

Training: 0it [00:00, ?it/s]Traceback (most recent call last):
raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'VitsLightning' object has no attribute '_temp_epoch'
Training: 0it [00:00, ?it/s]

**Comment by Lordmau5** [comment]
Meanwhile my generated one after 1600 steps (I merged the separate commits and didn't include the final one to fix the naming) seems to still be very metallic...

However, it does take the checkpoint into account, so that problem seems to be solved.
[generated_1599_v3_1_6.webm](https://user-images.githubusercontent.com/1345036/230783257-bfbc67ef-5c6e-4392-9f85-c71e8f4e4545.webm)

However, this does feel a bit.. strange..
Lightning claims to be ~2x faster for training, but if the results aren't on-part with "1x" of the previous method then there's no real positive of this, correct?

**Comment by 34j** [comment]
you may send a pr

**Comment by Lordmau5** [comment]
I updated my comment just now with a bit more info. 3.0.5 seems to yield better results than the current Lightning implementation.

However, since it is such a big change, I wouldn't even know what changed under the hood or what might need to be tweaked to give better results in Lightning, too... As in, which parameters and so on

**Comment by ne0escape** [comment]
> Just updated to 3.1.6, but getting this error:
> 
> Training: 0it [00:00, ?it/s]Traceback (most recent call last): raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'VitsLightning' object has no attribute '_temp_epoch' Training: 0it [00:00, ?it/s]

Line 184 in train.py

def __init__(self, reset_optimizer: bool = False, **hparams: Any):
    super().__init__()
    self._temp_epoch = 0  # Add this line to initialize the _temp_epoch attribute
    
This fixed it for me.

**Comment by Lordmau5** [comment]
> > Just updated to 3.1.6, but getting this error:
> > Training: 0it [00:00, ?it/s]Traceback (most recent call last): raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'VitsLightning' object has no attribute '_temp_epoch' Training: 0it [00:00, ?it/s]
> 
> Line 184 in train.py
> 
> ```
> def __init__(self, reset_optimizer: bool = False, **hparams: Any):
>     super().__init__()
>     self._temp_epoch = 0  # Add this line to initialize the _temp_epoch attribute
> ```
> 
> This fixed it for me.

Good addition, doesn't hurt to have

___
As for the weird metallic noise, I *think* I've managed to fix it by shifting some function calls around.

I removed one `with torch.no_grad():` call in train.py for the loss calculation.
It seems to slightly impact the speed (1.41it/s -> 1.33it/s) but I am getting a much better result.

Additionally, the following is the original code for optimization:
```
        # optimizer
        self.manual_backward(loss_gen_all)
        optim_g.step()
        optim_g.zero_grad()
        self.untoggle_optimizer(optim_g)
```

According to the Lightning.AI documentation, it should be as follow:
```
        # optimizer
        optim_g.zero_grad()
        self.manual_backward(loss_gen_all)
        optim_g.step()
        self.untoggle_optimizer(optim_g)
```
(Zero grad, manual backward, then step)
https://lightning.ai/docs/pytorch/stable/common/optimization.html#id2
https://lightning.ai/docs/pytorch/stable/common/lightning_module.html#manual-backward

This brings the speed down a bit more (1.33it/s -> 1.27it/s) but I believe it's the correct way to do it.
Unless the order you do it in actually makes more sense for training? (Manual backward, step, then zero grad)

Example of just 200 iterations on the LJ Speech dataset (~500 clips, even though it has WAY more):
[original_lj_speech.webm](https://user-images.githubusercontent.com/1345036/230791140-70bc3b0b-72a1-4e7a-ac71-d910d26d3dc9.webm)
[generated_lj_speech_200.webm](https://user-images.githubusercontent.com/1345036/230791147-8ff2b143-911e-4040-9875-bafbb3bb561e.webm)

I'll prep a PR in a second

**Comment by Lordmau5** [comment]
That only leaves the issue of checkpoints saving twice, and I couldn't figure that out yet...
![image](https://user-images.githubusercontent.com/1345036/230791575-1952334b-90fd-4f92-b4ed-db3c80f24c85.png)

**Comment by Meldoner** [comment]
@Lordmau5  so now is the latest version better than 3.0.5 or not?

**Comment by Meldoner** [comment]
i mean quality, not speed
