### ISSUE TITLE
improving google colab inference

### ISSUE THREAD

**Issue by Meldoner** [34j/so-vits-svc-fork#272]
**Is your feature request related to a problem? Please describe.**
I suggest making the .wav file download for inference from your google drive, because right now it is very inconvenient

**Describe the solution you'd like**
Change cell "Use trained model" from this:
#@title Use trained model
!svc infer {NAME}.wav -m drive/MyDrive/so-vits-svc-fork/logs/44k/ -c drive/MyDrive/so-vits-svc-fork/logs/44k/config.json
display(Audio(f"{NAME}.out.wav", autoplay=True))

To this:
#@title Use trained model
#@markdown **Put your audio file in `so-vits-svc-fork/audio` directory**
from IPython.display import Audio, display
NAME = 'YOUR AUDIO FILE NAME' #@param {type: "string"}
!svc infer drive/MyDrive/so-vits-svc-fork/audio/{NAME}.wav -m drive/MyDrive/so-vits-svc-fork/logs/44k/ -c drive/MyDrive/so-vits-svc-fork/logs/44k/config.json
display(Audio(f"drive/MyDrive/so-vits-svc-fork/audio/{NAME}.out.wav", autoplay=True))

**Comment by Meldoner** [comment]
and cell
`#@title Make dataset directory
%cd ./content`
is not needed, since we are originally in this directory

**Comment by BlueAmulet** [comment]
At the very least the dot should be removed from `./content`, the content folder should always be in the root of the colab filesystem.

**Comment by Meldoner** [comment]
> At the very least the dot should be removed from `./content`, the content folder should always be in the root of the colab filesystem.

content in colab is root, so this command is not needed at all

**Comment by 34j** [comment]
You can send a PR

**Comment by 34j** [comment]
You can send a PR
