### ISSUE TITLE
Error when running?

### ISSUE THREAD

**Issue by ThrowawayAccount01** [34j/so-vits-svc-fork#29]
Hi, I ran these in windows cmd:

`pip install -U torch torchaudio --index-url https://download.pytorch.org/whl/cu117`
`pip install so-vits-svc-fork`

then I ran `svcg`

but it gave me: `'svcg' is not recognized as an internal or external command,
operable program or batch file.`

please advise on how to fix this?

**Comment by 34j** [comment]
Are you using venv?
```
py -m venv venv
venv/scripts/activate
```

**Comment by ThrowawayAccount01** [comment]
I tried running

`py -m venv venv`
`venv/scripts/activate`

but I get: `'venv' is not recognized as an internal or external command,
operable program or batch file.`

I have no clue what venv is.

**Comment by 34j** [comment]
Okay, it's a pain in the ass, so please use the following command to start it up from Python.
```
python -c "from so_vits_svc_fork.gui import main;main()"
```

**Comment by ThrowawayAccount01** [comment]
I tried running `python -c "from so_vits_svc_fork.gui import main;main()"` but I get this error:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'so_vits_svc_fork'`

**Comment by 34j** [comment]
Your Python environment is a mess and you need to re-install it. This is not a problem with this repository.
