### ISSUE TITLE
Use RichProgressBar

### ISSUE THREAD

**Issue by Lordmau5** [34j/so-vits-svc-fork#308]
**Is your feature request related to a problem? Please describe.**
We already include the `rich` package, so we can use it's progress bar as described here:

It'll look like this:
![image](https://user-images.githubusercontent.com/1345036/231591900-57088cdb-5b26-49d3-a876-dcf628b637b6.png)

**Describe the solution you'd like**
To implement the RichProgressBar

**Additional context**
All that's needed is to modify the trainer initialization as follow:
```python
    trainer = pl.Trainer(
        accelerator="auto",
        logger=TensorBoardLogger(model_path),
        # profiler="simple",
        val_check_interval=hparams.train.eval_interval,
        max_epochs=hparams.train.epochs,
        check_val_every_n_epoch=None,
        precision="16-mixed"
        if hparams.train.fp16_run
        # else "bf16-mixed"
        else "bf16-mixed"
        if hparams.train.get("bf16_run", False)
        else 32,
        callbacks=[pl.callbacks.RichProgressBar()] # <-- Add this here
    )
```

Since it's a one-line change I don't see a huge need to turn this into a full pull request. I hope that's okay 🙏

**Comment by 34j** [comment]
I think it's fine. Please send a PR anyway.  (I would have to follow the same procedure if I were to do it)
