### ISSUE TITLE
Colab: Training steps / epochs not appearing on log, only D_0.pth and G_0.pth being created

### ISSUE THREAD

**Issue by outhipped** [34j/so-vits-svc-fork#321]
**Describe the bug**
Ttarining step does not work. The log shows:
2023-04-13 22:53:18.009147: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-13 22:53:19.311998: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[22:53:20] INFO     [22:53:20] NumExpr defaulting to 2 threads.     

**To Reproduce**
From step "Automatic preprocessing" onwards the log finishes at "NumExpr defaulting to 2 threads." message. 

**Additional context**
Stoped working 2 days ago. 

![Screenshot 2023-04-14 at 01 01 48](https://user-images.githubusercontent.com/116147475/231901199-4ebdcdf7-9be7-45ba-99b0-34ee1537bac5.png)

**Comment by 34j** [comment]
#317

**Comment by roseyyy2022ai** [comment]
So how exactly do I fix it? It stopped working for me as well today.

**Comment by roseyyy2022ai** [comment]
> #317 made this bug

How do I revert to like... a previous version or something (in colab)?

**Comment by 34j** [comment]
Probably it is working but simply not logging, probably

**Comment by outhipped** [comment]
That's what I begin to think to but it's still a bummer since Its useful to
know if it's progresses or not.

**Comment by roseyyy2022ai** [comment]
> Probably it is working but just not logging, probably

Nope. It's not working.
It's crasing after around one minute of running with a green checkmark too. No logs, no checkpoints. Nothing.

**Comment by estaesta** [comment]
> How do I revert to like... a previous version or something (in colab)?

u can install 33180e9 branch to revert to v3.5.0

**Comment by roseyyy2022ai** [comment]
Update: Just letting you all know. Apparently all releases have been "updated" to produce the same bug. I tried installing different releases/branches - still happening. Guess we're gonna have to wait until a new release with the *fix* for this "fix" lol.

**Comment by roseyyy2022ai** [comment]
> > How do I revert to like... a previous version or something (in colab)?
> 
> u can install [33180e9](https://github.com/34j/so-vits-svc-fork/commit/33180e9670b5f5282bee6b9344244c0281d7d21c) branch to revert to v3.5.0

Okay thanks that seems to *kind of* work but it still doesn't save checkpoints when I need to. Usually stopping the cell works just fine, 3.5 gives an eror and starts over every time. The end step seems to be set to 9999. Is there a way I can set it to something like 2500 instead?

**Comment by Lordmau5** [comment]
> #317 made this bug

The logic is inverted.
`callbacks=[pl.callbacks.RichProgressBar()] if is_notebook() else None,`

It uses the RichProgressBar if it **is** a notebook, not if it **isn't**

**Comment by axelblaze88** [comment]
> > #317 made this bug
> 
> The logic is inverted. `callbacks=[pl.callbacks.RichProgressBar()] if is_notebook() else None,`
> 
> It uses the RichProgressBar if it **is** a notebook, not if it **isn't**

What do you mean? Can you explain me how to solve it pls?

**Comment by Lordmau5** [comment]
> What do you mean? Can you explain me how to solve it pls?

Okay so, that code snippet checks if it's running in Colab. If it is, it will use the fancier progress bar.

However, this progress bar does not seem to be available inside Colab so 34j made this method to check.

The logic for it is the wrong way around though - instead of using the old / default progress bar in Colab when it detects it's running in Colab, it is using the fancy one that's not available.

The fix would be to do `if not is_notebook` instead.
___
I noticed this issue locally when the fancy progress bar wasn't available after an update.

If 34j (or someone else) won't be getting to a pull request I can do one once I'm back at my computer in around an hour

**Comment by axelblaze88** [comment]
> > What do you mean? Can you explain me how to solve it pls?
> 
> Okay so, that code snippet checks if it's running in Colab. If it is, it will use the fancier progress bar.
> 
> However, this progress bar does not seem to be available inside Colab so 34j made this method to check.
> 
> The logic for it is the wrong way around though - instead of using the old / default progress bar in Colab when it detects it's running in Colab, it is using the fancy one that's not available.
> 
> The fix would be to do `if not is_notebook` instead.
> 
> I noticed this issue locally when the fancy progress bar wasn't available after an update.
> 
> If 34j (or someone else) won't be getting to a pull request I can do one once I'm back at my computer in around an hour

Thank you!! ^^

**Comment by 831Digital** [comment]
I'm getting the same error @outhipped had right now when I try to train on colab. Switching to the 33180e9 branch works and allows me to train.

**Comment by 34j** [comment]
@allcontributors add outhipped bug
