### ISSUE TITLE
"TypedStorage is deprecated" while Training

### ISSUE THREAD

**Issue by MikuAuahDark** [34j/so-vits-svc-fork#330]
**Describe the bug**
Spammy "TypedStorage is deprecated" warning on every epoch.

```
[23:52:12] WARNING  [23:52:12] C:\omited\venv\lib\site-packages\torch\_utils.py:776: UserWarning:        warnings.py:109
                    TypedStorage is deprecated. It will be removed in the future and UntypedStorage will
                    be the only storage class. This should only matter to you if you are using storages
                    directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead
                    of tensor.storage()
                      return self.fget.__get__(instance, owner)()
```

**To Reproduce**
Simply train a voice.

**Additional context**
I updated to 3.6.1 today and start seeing the issue. Unfortunately I didn't know what was last good known version.

I'm training a voice using CREPE F0 predictor and using PyTorch 2.0.0 in Windows 11 if that matters.

**Comment by Lordmau5** [comment]
From my understanding this is an issue with *some* library / package that this project is utilizing, as I can't find any usage of `tensor.storage()` or `TypedStorage` in general in the code

I don't know *which* package is using it and if it already has an updated version that uses `UntypedStorage` instead
