### ISSUE TITLE
Spamming warnings in the console

### ISSUE THREAD

**Issue by Meldoner** [34j/so-vits-svc-fork#359]
**Describe the bug**
When I start inference in the GUI before the message about loading my model appears in the console, a lot of warnings are sent, but everything works fine

**To Reproduce**
Run the inference in the GUI using the latest version of fork

**Additional context**
It never happened before with the same model
Screenshot of warning:
![ShareX_AD40Nmwh0P](https://user-images.githubusercontent.com/43951115/232335035-e11de37a-ec27-4e4a-a18f-984aaf25264f.png)

**Comment by Lordmau5** [comment]
Which version are you on?

I did a pull request that should've suppressed those warnings (not errors) in 3.7.2

**Comment by Meldoner** [comment]
@Lordmau5  latest

**Comment by Lordmau5** [comment]
I see. 3.9.3 messed it up. There's an additional bug that I'll be reporting shortly.

https://github.com/34j/so-vits-svc-fork/commit/fd67db6312944557c09afd7b1ccbb97987a03489

Can you try downgrading to 3.9.2 and see if that fixes it?

**Comment by Lordmau5** [comment]
3.9.4 seems to have fixed this for me, can you check on your end again @Meldoner ?
