### ISSUE TITLE
Problem with saving the model

### ISSUE THREAD

**Issue by Meldoner** [34j/so-vits-svc-fork#361]
**Describe the bug**
the model is saved with the number of epochs and not the steps in the file name

**To Reproduce**
run training on google colab (or on your pc idk)

**Additional context**
Everything was fine before the update

**Comment by Lordmau5** [comment]
You need to override a config value since 3.9.0.
`ckpt_name_by_step`

https://github.com/34j/so-vits-svc-fork/commit/bba24c4a62b935ed29572aa2c2c437d1b54aa2e2

**Comment by Meldoner** [comment]
so, this is ok?

**Comment by Lordmau5** [comment]
Yeah, it seems intentional, not a bug :)
