### ISSUE TITLE
Can't stop voice changer (3.9.3)

### ISSUE THREAD

**Issue by Lordmau5** [34j/so-vits-svc-fork#367]
**Describe the bug**
With 3.9.3 switching to using the ThreadPool instead of the ProcessPool the voice changer can't be stopped anymore.

Additionally, this change also causes #359 .

**To Reproduce**
Start the voice changer on 3.9.3, then try to stop it. The console will say it was stopped but the logs about the inference will continue.

**Comment by Lordmau5** [comment]
Reading through people having similar issues, it seems setting `torch.multiprocessing.set_start_method('spawn')` in the `__main__` class at the bottom should fix it?

https://stackoverflow.com/questions/72779926/gunicorn-cuda-cannot-re-initialize-cuda-in-forked-subprocess
https://github.com/pytorch/pytorch/issues/40403

**Comment by 34j** [comment]
does not context=spawn work?

**Comment by Lordmau5** [comment]
You mean context=spawn for the Thread Pool? I'll give that a go.

I saw you tried that with the Process Pool before but commented it out

**Comment by 34j** [comment]
i didnt try it

**Comment by Lordmau5** [comment]
ThreadPool doesn't seem to have an argument called `context`. Do you mean you haven't tried it for ProcessPool?

**Comment by 34j** [comment]
Maybe multiprocessing.get_context('spawn')

**Comment by Lordmau5** [comment]
> Maybe multiprocessing.get_context('spawn')

Oh it could be I left that in as well and that'd what caused it, yes.

I should mention that since I'm on Windows I didn't encounter any issues with ProcessPool before - I can't test it on Linux unfortunately :(

**Comment by 34j** [comment]
#359 seems nothing to do with this

**Comment by Lordmau5** [comment]
> #359 seems nothing to do with this

It did, with ThreadPool. My assumption is that spawning the thread caused it to not initialize the logger correctly anymore in that thread.

3.9.4 fixed it though, since we're now back on the ProcessPool
