### ISSUE TITLE
Not installing properly

### ISSUE THREAD

**Issue by ItsMe-TJ** [34j/so-vits-svc-fork#44]
I can't seem to get it to install. 
Doing "pip install so-vits-svc-fork", but when I do 'svcg' or any other svc command, I get "'svcg' is not recognized as an internal or external command,
operable program or batch file.". I've tried anaconda as well, but getting the same thing.
Usually this means that It's not in the path, but doing "pip list" doesn't show it, so I assume It's not installing properly?

Any help would be appreciated.

**Comment by 34j** [comment]
I don't think it is installed correctly. Try again and copy paste all output.
