### ISSUE TITLE
how specify the anaconda venv when executing "svc train" ?

### ISSUE THREAD

**Issue by smallhaes** [34j/so-vits-svc-fork#48]
I confiure a anaconda venv for this project, but it seems that this program do not execute "svc train" with the venv i configured.  Could I specify the anaconda venv ?

**Comment by 34j** [comment]
I don't know because I have never used anaconda. I need help from others ......

**Comment by smallhaes** [comment]
您好，您的邮件已收到

**Comment by smallhaes** [comment]
> 

yes, I activate it. I'll try later. I would reply here if i figure it out.

**Comment by BlueAmulet** [comment]
If you're using anaconda, it has it's own virtual environment system separate from virtualenv/venv:

**To set up the environment:**
Create a new environment for so-vits-svc-fork, also adding in pip
```
conda create -n so-vits-svc-fork pip
```
Activate the environment
```
conda activate so-vits-svc-fork
```
Install pytorch and so-vits-svc-fork
```
pip install -U torch torchaudio --index-url https://download.pytorch.org/whl/cu117
pip install so-vits-svc-fork
```

**To use the environment and svc:**
Activate the environment:
```
conda activate so-vits-svc-fork
```
svc and svcg commands should now be available and use the conda environment that was created.

**Comment by 34j** [comment]
@allcontributors add BlueAmulet question

**Comment by smallhaes** [comment]
> If you're using anaconda, it has it's own virtual environment system separate from virtualenv/venv:
> 
> **To set up the environment:** Create a new environment for so-vits-svc-fork, also adding in pip
> 
> ```
> conda create -n so-vits-svc-fork pip
> ```
> 
> Activate the environment
> 
> ```
> conda activate so-vits-svc-fork
> ```
> 
> Install pytorch and so-vits-svc-fork
> 
> ```
> pip install -U torch torchaudio --index-url https://download.pytorch.org/whl/cu117
> pip install so-vits-svc-fork
> ```
> 
> **To use the environment and svc:** Activate the environment:
> 
> ```
> conda activate so-vits-svc-fork
> ```
> 
> svc and svcg commands should now be available and use the conda environment that was created.

Thanks! It works.
