### ISSUE TITLE
AlsaOpen error

### ISSUE THREAD

**Issue by nerdyrodent** [34j/so-vits-svc-fork#56]
**Describe the bug**
Audio does not play using svcg

**To Reproduce**
Steps to reproduce the behaviour:
1. svcg
2. select a .wav file under "input audio path"
3. press the "play" button

**Additional context**
The following error appears when trying to play:
```Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->playback, alsaApi, outParams, StreamDirection_Out, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2175
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2839
```
the .out.wav file is produced when clicking "infer" which can then be played normally.

**Comment by BlueAmulet** [comment]
soundfile and libsndfile don't use portaudio, which is where those error messages come from.
sounddevice does use portaudio, and the second error message indicates audio output failure.

**Comment by 34j** [comment]
I see, I made a pointless change.

**Comment by 34j** [comment]
I forgot about #72.
