### ISSUE TITLE
Input/Output Device List duplication

### ISSUE THREAD

**Issue by ThrowawayAccount01** [34j/so-vits-svc-fork#90]
The list of devices in the Input/Output dropdown list seems to duplicate itself further down the list.

![01](https://user-images.githubusercontent.com/125531852/227397313-2ca9ced8-fe21-41a6-9137-955966b8b686.png)

**Comment by 34j** [comment]
The protocols used are different, such as asio, wasapi...

**Comment by ThrowawayAccount01** [comment]
Is it possible to make it list the different protocols so its a bit clearer?

Also, the dropdown list is very small and cutting off some of the text. Is it possible to make it larger so its easier to read?

**Comment by 34j** [comment]
Too righteous for words.😂
